version: 2

sources:
  - name: googles_analytics_4
    schema: google_analytics_4
    tables:
      - name: events_2021_01_05
      
  - name: google_sheets
    schema: google_sheets
    tables:
      - name: data_google_sheets

  - name: dataset_fil_rouge
    schema: dataset_fil_rouge
    tables:
      - name: feedback
      - name: payment
      - name: product
      - name: order
      - name: order_item
      - name: seller
      - name: user

  - name: spotify
    schema: spotify
    tables:
      - name: songs
      - name: listening_data

  - name: airbnb
    schema: airbnb
    tables:
      - name: listings